
package bioskopapp.gui;

import bioskopapp.dao.AdminDAO; 
import javax.swing.JOptionPane;
import javax.swing.JFrame;

public class MainMenuFrame extends javax.swing.JFrame {

    
    public MainMenuFrame() {
        initComponents();
        setupFrameProperties();
    }
    
    private void setupFrameProperties() {
        this.setTitle("Sistem Pemesanan Tiket Bioskop - Menu Utama");
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnAdminLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUserBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bioskop RGAJ");
        setPreferredSize(new java.awt.Dimension(1540, 840));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Bioskop RGAJ");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 31, -1, -1));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setText("Username : ");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 43, -1, -1));

        txtUsername.setToolTipText("Masukkan username admin");
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 43, 110, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword.setText("Password :");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 43, -1, -1));

        txtPassword.setToolTipText("Masukkan password admin");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 43, 112, -1));

        btnAdminLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdminLogin.setText("Login");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1077, 40, 133, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Tekan Untuk Melihat Daftar Film");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 620, -1));

        btnUserBooking.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\java\\102.jpg")); // NOI18N
        btnUserBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserBookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1295, -1));

        setBounds(0, 0, 1239, 847);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword()); 

        AdminDAO adminDAO = new AdminDAO(); 
        try {
            if (adminDAO.authenticate(username, password)) {
                JOptionPane.showMessageDialog(this, "Login Admin Berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                AdminDashboardFrame adminDashboard = new AdminDashboardFrame();
                adminDashboard.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Username atau password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat login: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnUserBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserBookingActionPerformed
        UserBookingFrame userBooking = new UserBookingFrame();
        userBooking.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnUserBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
