
package bioskopapp.gui;

import bioskopapp.dao.TransactionDAO;
import bioskopapp.model.TransactionDetail;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



public class SalesReportPanel extends javax.swing.JPanel {

    
    private TransactionDAO transactionDAO;
    private DefaultTableModel tableModel;

    
    public SalesReportPanel() {
        initComponents();
        transactionDAO = new TransactionDAO();
        applyCustomStyles();
        setupTable();
        loadReportData();
    }
    
    private void applyCustomStyles() {
        lblMainTitle.setFont(new Font("Segoe UI", Font.BOLD, 18));
        
        JTableHeader header = tblReports.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 12));
        header.setBackground(new Color(240, 240, 240));
        tblReports.setRowHeight(28);
        
        lblTotalRevenue.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblTotalRevenueValue.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblTotalRevenueValue.setForeground(new Color(0, 153, 51));
    }

    private void setupTable() {
        tableModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID Transaksi", "Judul Film", "Jadwal Tayang", "Kursi", "Nama Pemesan", "Total Bayar", "Waktu Pesan"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblReports.setModel(tableModel);
    }
    
    public void loadReportData() {
        tableModel.setRowCount(0);
        double totalRevenue = 0;
        
        try {
            
            List<TransactionDetail> transactionDetails = transactionDAO.getTransactionDetails();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMM uuuu, HH:mm");
            DecimalFormat currencyFormatter = new DecimalFormat("'Rp '###,##0");

            for (TransactionDetail detail : transactionDetails) {
                tableModel.addRow(new Object[]{
                    detail.getTransactionId(),
                    detail.getFilmTitle(),
                    detail.getScheduleInfo(),
                    detail.getSeatNumbers(),
                    detail.getCustomerName(),
                    currencyFormatter.format(detail.getTotalPrice()),
                    detail.getTransactionTime().format(formatter)
                });
                totalRevenue += detail.getTotalPrice();
            }
            
            lblTotalRevenueValue.setText(currencyFormatter.format(totalRevenue));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainTitle = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        lblTotalRevenue = new javax.swing.JLabel();
        lblTotalRevenueValue = new javax.swing.JLabel();

        lblMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainTitle.setText("Laporan Penjualan Tiket");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReports);

        lblTotalRevenue.setText("Total Pendapatan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRefresh)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(181, 181, 181)
                            .addComponent(lblMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTotalRevenue)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotalRevenueValue, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMainTitle)
                .addGap(24, 24, 24)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalRevenue)
                .addGap(18, 18, 18)
                .addComponent(lblTotalRevenueValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadReportData();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JLabel lblTotalRevenueValue;
    private javax.swing.JTable tblReports;
    // End of variables declaration//GEN-END:variables
}
