package bioskopapp.gui;

import bioskopapp.dao.FilmDAO;
import bioskopapp.model.Film;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public class UserBookingFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserBookingFrame
     */
    public UserBookingFrame() {
        initComponents();
        
        // --- Kode Kustom Anda ---
        loadFilmsToGrid();
        this.setLocationRelativeTo(null); // Agar frame muncul di tengah layar
        this.setTitle("Pemesanan Tiket Bioskop - Pilih Film");

        // Menambahkan listener untuk tombol close ('X') pada frame
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                goBackToMainMenu();
            }
        });
    }

    /**
     * Kembali ke menu utama dan menutup frame ini.
     */
    private void goBackToMainMenu() {
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }

    /**
     * Mengambil data film dari database dan menampilkannya di panel grid.
     */
    private void loadFilmsToGrid() {
        FilmDAO filmDAO = new FilmDAO();
        try {
            // Bersihkan panel sebelum menambahkan kartu baru
            panelFilmGrid.removeAll();

            List<Film> films = filmDAO.getAllFilms();
            if (films.isEmpty()) {
                panelFilmGrid.add(new JLabel("Tidak ada film yang sedang tayang."));
            } else {
                for (Film film : films) {
                    // Buat kartu untuk setiap film dan tambahkan ke panel
                    JPanel card = createFilmCard(film);
                    panelFilmGrid.add(card);
                }
            }

            // Perbarui UI untuk menampilkan perubahan
            panelFilmGrid.revalidate();
            panelFilmGrid.repaint();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data film.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Membuat sebuah JPanel yang berfungsi sebagai kartu visual untuk satu film.
     * @param film Objek film yang akan ditampilkan.
     * @return JPanel yang berisi poster dan judul film.
     */
    private JPanel createFilmCard(Film film) {
        JPanel card = new JPanel(new BorderLayout(10, 10));
        card.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(220, 220, 220)));
        card.setCursor(new Cursor(Cursor.HAND_CURSOR));

        JLabel posterLabel = new JLabel();
        posterLabel.setHorizontalAlignment(SwingConstants.CENTER);
        posterLabel.setPreferredSize(new Dimension(320, 520));

        if (film.getPosterPath() != null && new File(film.getPosterPath()).exists()) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(film.getPosterPath());
            Image image = icon.getImage().getScaledInstance(320, 520, Image.SCALE_SMOOTH);
            posterLabel.setIcon(new javax.swing.ImageIcon(image));
        } else {
            posterLabel.setText("No Poster");
        }

        JLabel titleLabel = new JLabel("<html><center>" + film.getJudul() + "</center></html>", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 24));
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 150, 0));


        card.add(posterLabel, BorderLayout.CENTER);
        card.add(titleLabel, BorderLayout.SOUTH);

        // Menambahkan aksi saat kartu film di-klik
        card.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Buka frame pemilihan kursi dengan mengirim data film yang dipilih
                SeatSelectionFrame seatFrame = new SeatSelectionFrame(film);
                seatFrame.setVisible(true);
                // Tutup frame ini
                UserBookingFrame.this.dispose();
            }
        });

        return card;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneFilms = new javax.swing.JScrollPane();
        panelFilmGrid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFilmGrid.setLayout(new java.awt.GridLayout(1, 4, 20, 20));
        scrollPaneFilms.setViewportView(panelFilmGrid);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Sedang Tayang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneFilms)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(671, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(666, 666, 666))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneFilms, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserBookingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelFilmGrid;
    private javax.swing.JScrollPane scrollPaneFilms;
    // End of variables declaration//GEN-END:variables
}
