package bioskopapp.gui;

import bioskopapp.dao.FilmDAO;
import bioskopapp.model.Film;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public class UserBookingFrame extends javax.swing.JFrame {

    public UserBookingFrame() {
        initComponents();
        
        loadFilmsToGrid();
        this.setLocationRelativeTo(null);
        this.setTitle("Pemesanan Tiket Bioskop - Pilih Film");

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                goBackToMainMenu();
            }
        });
    }

    
    private void goBackToMainMenu() {
        new MainMenuFrame().setVisible(true);
        this.dispose();
    }

    
    private void loadFilmsToGrid() {
        FilmDAO filmDAO = new FilmDAO();
        try {
            panelFilmGrid.removeAll();

            List<Film> films = filmDAO.getAllFilms();
            if (films.isEmpty()) {
                panelFilmGrid.add(new JLabel("Tidak ada film yang sedang tayang."));
            } else {
                for (Film film : films) {
                    JPanel card = createFilmCard(film);
                    panelFilmGrid.add(card);
                }
            }

            panelFilmGrid.revalidate();
            panelFilmGrid.repaint();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data film.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private JPanel createFilmCard(Film film) {
        JPanel card = new JPanel(new BorderLayout(10, 10));
        card.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(220, 220, 220)));
        card.setCursor(new Cursor(Cursor.HAND_CURSOR));

        JLabel posterLabel = new JLabel();
        posterLabel.setHorizontalAlignment(SwingConstants.CENTER);
        posterLabel.setPreferredSize(new Dimension(320, 520));

        if (film.getPosterPath() != null && new File(film.getPosterPath()).exists()) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(film.getPosterPath());
            Image image = icon.getImage().getScaledInstance(320, 520, Image.SCALE_SMOOTH);
            posterLabel.setIcon(new javax.swing.ImageIcon(image));
        } else {
            posterLabel.setText("No Poster");
        }

        JLabel titleLabel = new JLabel("<html><center>" + film.getJudul() + "</center></html>", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 24));
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 150, 0));


        card.add(posterLabel, BorderLayout.CENTER);
        card.add(titleLabel, BorderLayout.SOUTH);

        card.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                SeatSelectionFrame seatFrame = new SeatSelectionFrame(film);
                seatFrame.setVisible(true);
                UserBookingFrame.this.dispose();
            }
        });

        return card;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneFilms = new javax.swing.JScrollPane();
        panelFilmGrid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFilmGrid.setLayout(new java.awt.GridLayout(1, 4, 20, 20));
        scrollPaneFilms.setViewportView(panelFilmGrid);

        getContentPane().add(scrollPaneFilms, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 1540, 610));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sedang Tayang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 6, -1, 64));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/new-years-eve-1085072_1280.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 830));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/new-years-eve-1085072_1280.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1290, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserBookingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserBookingFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelFilmGrid;
    private javax.swing.JScrollPane scrollPaneFilms;
    // End of variables declaration//GEN-END:variables
}
